theme: jekyll-theme-slate
title: Evolutionary Verification of Consistency Properties in Software Product Lines
description: The Companion Website
show_downloads: false
github: [metadata]
sub_pages:
    - title: Home
      url: /
    - title: About
      url: /about
    - title: Downloads
      url: /downloads